apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-advanced
  annotations:
    # This annotation ensures Projects (Namespaces) are created first when deployed via Argo CD
    argocd.argoproj.io/sync-wave: "-1"
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
    - stage: staging
      autoPromotionEnabled: true
    - stage: prod-east
      autoPromotionEnabled: true
    - stage: prod-west
      autoPromotionEnabled: true
    - stage: prod-central
      autoPromotionEnabled: true
