apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: green
spec:
  subscriptions:
    warehouse: guestbook
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/vojtechmares/kargo-advanced.git
        writeBranch: env/dev
        render: {}
    argoCDAppUpdates:
      - appName: guestbook-dev
  verification:
    analysisTemplates:
      - name: cat-fact

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: amber
spec:
  subscriptions:
    upstreamStages:
      - name: dev
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/vojtechmares/kargo-advanced.git
        writeBranch: env/staging
        render: {}
    argoCDAppUpdates:
      - appName: guestbook-staging
  verification:
    analysisTemplates:
      - name: job

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-west
  namespace: kargo-advanced
  annotations:
    kargo.akuity.io/color: blue
spec:
  subscriptions:
    upstreamStages:
      - name: staging
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/vojtechmares/kargo-advanced.git
        writeBranch: env/prod-west
        render: {}
    argoCDAppUpdates:
      - appName: guestbook-prod-west
  verification:
    analysisTemplates:
      - name: cat-fact
